views:
  - title: Main
    cards:
      - type: custom:mini-graph-card
        entities:
          - sensor.humidity
      - type: custom:mini-graph-card
        entities:
          - sensor.temperature
      - type: custom:mini-graph-card
        entities:
          - sensor.pressure
        show:
          extrema: true
        # decimals: 10
